name: Test Corretto Java Versions with .tool-versions

on: [push, pull_request]

jobs:
  test-setup-java:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-version:
           # Corretto
          - "corretto-8.202.08.2"
          - "corretto-11.0.28.6.1"
          - "corretto-15.0.2.7.1"
          - "corretto-16.0.0.36.1"
          - "corretto-17.0.16.8.1"
          - "corretto-18.0.2.9.1"
          - "corretto-19.0.2.7.1"
          - "corretto-20.0.2.10.1"
          - "corretto-21.0.8.9.1"
          - "corretto-22.0.2.9.1"
          - "corretto-23.0.2.7.1"
          - "corretto-24.0.2.12.1"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .tool-versions with ASDF format
        run: |
          echo "java ${{ matrix.java-version }}" > .tool-versions
          cat .tool-versions

      - name: Test setup-java from PR branch
        uses: aparnajyothi-y/setup-java@toolversions-regex-update
        with:
          distribution: 'corretto'
          java-version-file: '.tool-versions'

      - name: Verify Java installation
        run: java -version