name: Test EA version

on:
  push:
    branches:
      - jetbrains-test
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest, macos-13, ubuntu-24.04-arm, windows-11-arm] # Include macos-latest for all except where overridden
        ea: ['21.0.5-ea', '21-ea'] # Add EA versions to test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: priyagupta108/setup-java@jetbrains-fix-test
        with:
          distribution: 'jetbrains'
          java-version: ${{ matrix.ea }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  

      - name: Verify Java version
        run: java -version
