name: Test EA version

on:
  push:
    branches:
      - graalVm-test
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest, macos-13, ubuntu-24.04-arm, windows-11-arm] # Include macos-latest for all except where overridden
        ea: ['21.0.5-ea', '21.0.4-ea', '21-ea', '17-ea'] # Add EA versions to test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: mahabaleshwars/setup-java@fix/graalvm-api-rate-limit
        with:
          distribution: 'graalvm'
          java-version: ${{ matrix.ea }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  

      - name: Verify Java version
        run: java -version
