name: Test JetBrains Java Versions with .tool-versions

on: [push, pull_request]

jobs:
  test-setup-java:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-version:
          # JetBrains
          - "jetbrains-11.0.16b2043.64"
          - "jetbrains-17.0.14b1367.22"
          - "jetbrains-21.0.7b1038.58"
          - "jetbrains-jre-11.0.16b2043.64"
          - "jetbrains-jre-17.0.14b1367.22"
          - "jetbrains-jre-21.0.2b346.3"
          - "jetbrains-jre-21.0.7b1038.58"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .tool-versions with ASDF format
        run: |
          echo "java ${{ matrix.java-version }}" > .tool-versions
          cat .tool-versions

      - name: Test setup-java from PR branch
        uses: aparnajyothi-y/setup-java@toolversions-regex-update
        with:
          distribution: 'jetbrains'
          java-version-file: '.tool-versions'

      - name: Verify Java installation
        run: java -version