name: Test Liberica Java Versions with .tool-versions

on: [push, pull_request]

jobs:
  test-setup-java:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-version:
           # Liberica
          - "liberica-1.8.0"
          - "liberica-8u202"
          - "liberica-8u432+7"
          - "liberica-12"
          - "liberica-13.0.2+9"
          - "liberica-15.0.2+10"
          - "liberica-16.0.2+7"
          - "liberica-17.0.16+12"
          - "liberica-18+37"
          - "liberica-19.0.2+9"
          - "liberica-20.0.2+10"
          - "liberica-21+37"
          - "liberica-24.0.2+12"
          - "liberica-javafx-8u242+7"
          - "liberica-javafx-11.0.18+10"
          - "liberica-javafx-14.0.2+13"
          - "liberica-javafx-15+36"
          - "liberica-javafx-17.0.14+10"
          - "liberica-javafx-21.0.6+10"
          - "liberica-javafx-24.0.2+12"
          - "liberica-jre-1.8.0"
          - "liberica-jre-8u232"
          - "liberica-jre-8u462+11"
          - "liberica-jre-11.0.15.1+2"
          - "liberica-jre-14.0.1+8"
          - "liberica-jre-24.0.2+12"
          - "liberica-jre-javafx-8u242+7"
          - "liberica-jre-javafx-11.0.15.1+2"
          - "liberica-jre-javafx-24.0.2+12"
          - "liberica-lite-8u462+11"
          - "liberica-lite-11.0.5"
          - "liberica-lite-21+37"
          - "liberica-lite-22.0.2+11"
          - "liberica-lite-23.0.2+9"
          - "liberica-lite-24.0.2+12"
          - "liberica-16+36"
          - "liberica-11.0.10+9"
          - "liberica-javafx-16+36"
          - "liberica-javafx-11.0.10+9"
          - "liberica-jre-16+36"
          - "liberica-jre-11.0.10+9"
          - "liberica-jre-javafx-16+36"
          - "liberica-jre-javafx-11.0.10+9"
          - "liberica-lite-16+36"
          - "liberica-lite-11.0.10+9"
           # Newer versions
          - "liberica-11.0.14.1+1"
          - "liberica-8u282+8"
          - "liberica-javafx-11.0.14.1+1"
          - "liberica-javafx-8u282+8"
          - "liberica-jre-11.0.14.1+1"
          - "liberica-jre-8u282+8"
          - "liberica-jre-javafx-11.0.14.1+1"
          - "liberica-jre-javafx-8u282+8"
          - "liberica-lite-11.0.14.1+1"
          - "liberica-lite-8u302+8"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .tool-versions with ASDF format
        run: |
          echo "java ${{ matrix.java-version }}" > .tool-versions
          cat .tool-versions

      - name: Test setup-java from PR branch
        uses: aparnajyothi-y/setup-java@toolversions-regex-update
        with:
          distribution: 'liberica'
          java-version-file: '.tool-versions'

      - name: Verify Java installation
        run: java -version