name: Maven Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '17'
    - name: Build with Maven
      run: mvn package
    - name: Run App
      run: java -cp target/sample-java-1.0-SNAPSHOT.jar com.example.App