name: Test Oracle Java Versions with .tool-versions

on: [push, pull_request]

jobs:
  test-setup-java:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-version:
         # Oracle
          - "oracle-17"
          - "oracle-18.0.1.1"
          - "oracle-24"
          - "oracle-24.0.1"
          - "oracle-24.0.2"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .tool-versions with ASDF format
        run: |
          echo "java ${{ matrix.java-version }}" > .tool-versions
          cat .tool-versions

      - name: Test setup-java from PR branch
        uses: aparnajyothi-y/setup-java@toolversions-regex-update
        with:
          distribution: 'oracle'
          java-version-file: '.tool-versions'

      - name: Verify Java installation
        run: java -version