name: Test Setup Java sapmachine PR#767

on: [push, pull_request]

jobs:
  test-setup-java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .tool-versions with ASDF format
        run: |
          echo "java sapmachine-17" > .tool-versions
          cat .tool-versions

      - name: Test setup-java from PR branch
        uses: actions/setup-java@refs/pull/767/merge
        with:
          distribution: 'sapmachine'
          java-version-file: '.tool-versions'

      - name: Verify Java installation
        run: java -version