name: Test Setup Java temurin PR#767

on: [push, pull_request]

jobs:
  test-setup-java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .tool-versions with ASDF format
        run: |
          echo "java temurin-11.0.15+10" > .tool-versions
          cat .tool-versions

      - name: Test setup-java from PR branch
        uses: aparnajyothi-y/setup-java@toolversions-regex-update
        with:
          distribution: 'temurin'
          java-version-file: '.tool-versions'

      - name: Verify Java installation
        run: java -version