name: Test PublishinG to GPR using Gradle

on:
  # push:
  #   branches:
  #     - sapMachine

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: Shegox/setup-java@main
      with:
        distribution: 'sapmachine'
        java-version: '21'

    
