name: Test check-latest option

on:
  push:
    branches:
      - jetbrains-test

  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest, macos-13, ubuntu-24.04-arm, windows-11-arm]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: priyagupta108/setup-java@fix-JetBrains-install
      with:
        distribution: 'jetbrains'
        java-version: '21'
        check-latest: true
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
 

    - name: Verify Java version
      run: java -version

    