name: Test env

on:
  push:
    branches:
      - graalVm-test

  workflow_dispatch:
env:
   MY_NAME: 'Priya'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest, macos-13, ubuntu-24.04-arm, ]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: priyagupta108/setup-java@test-log
      with:
        distribution: 'graalvm'
        java-version: '21'
        check-latest: true
    

    - name: Verify Java version
      run: java -version

    
