name: Test java Windows zip issue

on:
  push:
    branches:
      - sapMachine
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, win-10-pro-x64]
    strategy:
      fail-fast: false
      matrix:
        distribution: [ 'adopt', 'zulu', 'temurin', 'corretto', 'liberica', 'oracle', 'microsoft', 'semeru', 'dragonwell', 'sapmachine', graalvm]

    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.distribution }}
          java-version: '21'

     