name: Test java Windows zip issue

on:
  push:
    branches:
      - sapMachine
  workflow_dispatch:
  

jobs:
  test:
    runs-on: [self-hosted, win-10-pro-x64]
    strategy:
      fail-fast: false
      matrix:
        distribution: [ 'adopt', 'zulu', 'temurin', 'corretto', 'liberica', 'oracle', 'microsoft', 'semeru', 'dragonwell', 'sapmachine', graalvm]
        
    steps:
      # - name: cache clear
      #   run: |
      #     mv "${{ runner.tool_cache }}" "${{ runner.tool_cache }}.old"
      #     mkdir -p "${{ runner.tool_cache }}"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        # uses: priyagupta108/setup-java@fix-windows-archive-extraction
        uses: actions/setup-java@main
        with:
          distribution: ${{ matrix.distribution }}
          java-version: '21'
          cache: 'gradle'
  

      - name: Verify Java version
        run: java -version
