name: Test java Windows zip issue

on:
  push:
    branches:
      - sapMachine
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, win-10-pro-x64]
    strategy:
      fail-fast: false
      matrix:
        build-system: ['maven', 'sbt']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: priyagupta108/setup-java@fix-windows-archive-extraction
        with:
          distribution: 'adopt'
          java-version: '21'
          cache: ${{ matrix.build-system }}

      - name: Setup Environment on Windows ARM64 Runner
        shell: powershell
        run: |
         
          # Install curl
          choco install curl -y
          echo "C:\ProgramData\chocolatey\bin" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8

      - name: Download and Install Maven
        if: matrix.build-system == 'maven'
        run: |
          curl -O https://downloads.apache.org/maven/maven-3/3.8.5/binaries/apache-maven-3.8.5-bin.zip
          tar -xvf apache-maven-3.8.5-bin.zip
          echo "MAVEN_HOME=$(pwd)/apache-maven-3.8.5" >> $GITHUB_ENV
          echo "$(pwd)/apache-maven-3.8.5/bin" >> $GITHUB_PATH

      - name: Download and Install sbt
        if: matrix.build-system == 'sbt'
        run: |
          curl -L -o sbt.zip https://github.com/sbt/sbt/releases/download/v1.5.5/sbt-1.5.5.zip
          tar -xvf sbt.zip
          echo "SBT_HOME=$(pwd)/sbt" >> $GITHUB_ENV
          echo "$(pwd)/sbt/bin" >> $GITHUB_PATH

      - name: Build with Maven
        if: matrix.build-system == 'maven'
        run: mvn -B package --file pom.xml

      - name: Build with SBT
        if: matrix.build-system == 'sbt'
        run: sbt package

      - name: Verify Java version
        run: java -version