name: Python workflow
on:
  # push:
  workflow_dispatch:
jobs:
  build:
    runs-on: [self-hosted, win-10-pro-x64]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11.6
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Display Python version
      run: python --version
