name: Test java Windows zip issue

on:
  push:
    branches:
      - sapMachine
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, windows10-Enter]
    strategy:
      fail-fast: false
      matrix:
        distribution: [ 'adopt', 'zulu', 'temurin', 'corretto', 'liberica', 'oracle', 'microsoft', 'semeru', 'dragonwell', 'sapmachine', graalvm]
       
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: priyagupta108/setup-java@fix-windows-archive-extraction
        with:
          distribution: ${{ matrix.distribution }}
          java-version: '21'
          

     