# name: Test Win zip issue in Windows 10 Enterprise, 64 bit

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:
  

# jobs:
#   test:
#     runs-on: [self-hosted, windows10-Enter]
#     strategy:
#       fail-fast: false
#       matrix:
#         distribution: [ 'adopt', 'zulu', 'temurin', 'corretto', 'liberica', 'oracle', 'microsoft', 'semeru', 'dragonwell', 'sapmachine', graalvm]
        
#     steps:
#       # - name: cache clear
#       #   run: |
#       #     mv "${{ runner.tool_cache }}" "${{ runner.tool_cache }}.old"
#       #     mkdir -p "${{ runner.tool_cache }}"

#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Java
#         # uses: priyagupta108/setup-java@winZip
#         uses: actions/setup-java@main
#         with:
#           distribution: ${{ matrix.distribution }}
#           java-version: '21'
  

#       - name: Verify Java version
#         run: java -version
name: Test of downloading corretto with actions/setup-java@v4

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    runs-on: [ self-hosted, windows10-Enter ]

    steps:

    - name: Setup Java Corretto
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '11'
        # tried overwrite-settings: false  and also true.
        overwrite-settings: false
        check-latest: true
        cache: maven

    - name: Check java version
      shell: cmd
      run: java -version