name: GraalVM smoke tests

on:
  push:
permissions: read-all
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-13, windows-2022, ubuntu-latest, windows-latest, macos-latest]
        java-version: [21, 23, 17]

    steps:
      - uses: actions/checkout@v4
    
      - name: Set up GraalVM 
        uses: actions/setup-java@v4
        with:
            distribution: 'graalvm'
            java-version:  ${{ matrix.java-version }}
        
      
