name: Adopt test https://github.com/actions/setup-java/issues/692
on:
  push:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, ubuntu-latest, windows-latest, macos-latest, ubuntu-22.04]
        java-version: [21, 17, 11]

    steps:
      - uses: actions/checkout@v4
    
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java-version }}
              
      
