name: GraalVM smoke tests

on:
  push:
permissions: read-all
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, ubuntu-latest, windows-latest, macos-latest]
        # java-version: [21, 23, 17.0.12, 22]

    steps:
      - uses: actions/checkout@v4
    
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adoptium'
          java-version: 17
              
      
