name: Test Java Windows zip issue

on:
  push:
    branches:
      - sapMachine
  workflow_dispatch:

jobs:
  test-with-v4:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            distribution: 'zulu'
            java-version: '17'
            architecture: 'x64'
          - os: self-hosted
            label: win-10-pro-x64
            distribution: 'zulu'
            java-version: '17'
            architecture: 'x86'
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java-version }}
          architecture: ${{ matrix.architecture }}
  test-with-fix:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            distribution: 'zulu'
            java-version: '21'
            architecture: 'x64'
          - os: self-hosted
            label:  win-10-pro-x64
            distribution: 'zulu'
            java-version: '21'
            architecture: 'x86'
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: priyagupta108/setup-java@fix-windows-archive-extraction
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java-version }}
          architecture: ${{ matrix.architecture }}
