name: Test Zulu Java Versions with .tool-versions

on: [push, pull_request]

jobs:
  test-setup-java:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-version:
         # Zulu
          - zulu-javafx-11.45.27
          - zulu-jre-11.45.27
          - zulu-jre-javafx-11.45.27
          - zulu-8.52.0.23
          - zulu-javafx-8.52.0.23
          - zulu-jre-8.52.0.23
          - zulu-jre-javafx-8.52.0.23
          # Newer versions
          - zulu-8.62.0.19_1
          - zulu-11.66.15_1
          - zulu-javafx-11.66.15_1
          - zulu-jre-11.66.15_1
          - zulu-jre-javafx-11.66.15_1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .tool-versions with ASDF format
        run: |
          echo "java ${{ matrix.java-version }}" > .tool-versions
          cat .tool-versions

      - name: Test setup-java from PR branch
        uses: aparnajyothi-y/setup-java@toolversions-regex-update
        with:
          distribution: 'zulu'
          java-version-file: '.tool-versions'

      - name: Verify Java installation
        run: java -version